### ISSUE TITLE
订阅号出现随机发送消息

### ISSUE THREAD

**Issue by canyuegongzi** [gengchen528/wechat-assistant#2]
机器人随机在订阅号里发送消息，如果这个公众号恰好也有机器人，出现了循环对话！

**Comment by gengchen528** [comment]
目前会出现这个问题，可以进行判断一下消息内容，超过多少字符后不进行回复

**Comment by setsuna** [comment]
获取任务列表错误 Error: socket hang up
    at connResetException (internal/errors.js:559:14)
    at Socket.socketOnEnd (_http_client.js:436:23)
    at Socket.emit (events.js:205:15)
    at Socket.EventEmitter.emit (domain.js:471:20)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  code: 'ECONNRESET',
  response: undefined
}

**Comment by gengchen528** [comment]
需要开启koa服务的 ，文件在`config/koa.js`
